[supervisord]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
nodaemon=true
user=root

[program:rpikabufeedbot]
command=bash -c 'sleep 30 && php ./src/Cron.php'
stdout_events_enabled=true
stderr_events_enabled=true
directory=/app
autostart=true
autorestart=true
user=root
